AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront Stack - Scalable Web App'

Parameters:
  ProjectName:
    Type: String
    Default: scalable-web-app

Resources:

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: ALBOrigin
            DomainName: !ImportValue
              Fn::Sub: ${ProjectName}-ALBDNSName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Enabled: true
        Comment: !Sub ${ProjectName} CloudFront Distribution
        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
        CacheBehaviors:
          - PathPattern: /static/*
            TargetOriginId: ALBOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
        PriceClass: PriceClass_100
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-cf

Outputs:
  CloudFrontURL:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${ProjectName}-CloudFrontURL

  CloudFrontId:
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${ProjectName}-CloudFrontId