AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS Stack - Scalable Web App'

Parameters:
  ProjectName:
    Type: String
    Default: scalable-web-app
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: RDS Master Password

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !ImportValue
          Fn::Sub: ${ProjectName}-PrivateSubnet1
        - !ImportValue
          Fn::Sub: ${ProjectName}-PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-db-subnet-group

  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-db
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: '8.0'
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBName: appdb
      AllocatedStorage: '20'
      StorageType: gp2
      MultiAZ: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !ImportValue
          Fn::Sub: ${ProjectName}-RDSSecurityGroup
      BackupRetentionPeriod: 7
      StorageEncrypted: true
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-rds

Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub ${ProjectName}-RDSEndpoint